# Read subjects and stories for secondlevel analysis

In [1]:
import pandas as pd
import os
import shutil
from subprocess import run

/home/xy6/.local/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [2]:
mastersheetFile = '/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/master/codes/master_subject_10stories_highacc.csv'
df_master = pd.read_csv(mastersheetFile)
df_master

,subID,task,age,sex,condition,comprehension,transcript,label,confounding,smooth_clean,nosmooth_clean,smooth_clean_rs,nosmooth_clean_rs,event
0,sub-023,prettymouth,28,F,affair,0.889,prettymouth,prettymouth,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
1,sub-023,milkyway,28,F,vodka,1.000,milkywayvodka,milkywayvodka,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
2,sub-030,prettymouth,21,F,paranoia,0.963,prettymouth,prettymouth,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
3,sub-030,milkyway,21,F,vodka,0.893,milkywayvodka,milkywayvodka,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
4,sub-032,prettymouth,22,M,affair,0.963,prettymouth,prettymouth,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
208,sub-314,piemanpni,25,F,NaN,0.767,piemanpni,piemanpni,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
209,sub-314,bronx,25,F,NaN,0.780,bronx,bronx,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
210,sub-314,forgot,25,F,NaN,0.780,forgot,forgot,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
211,sub-314,black,25,F,NaN,0.920,black,black,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...
212,sub-315,black,35,M,NaN,0.600,black,black,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...,/work/desai-lab/xuanyang/Project/dataset/Nasta...

In [4]:
df_master

(213, 14)

In [3]:
import subprocess
import pandas as pd

def get_subbricks_info(dataset):
    # Run 3dinfo command
    result = subprocess.run(['/work/apps/AFNI/linux_openmp_64/3dinfo', '-verb', dataset], capture_output=True, text=True)
    lines = result.stdout.split('\n')
    
    # Extract lines with sub-brick info
    subbrick_lines = [line for line in lines if "sub-brick" in line]
    
    # Extract indices and names from those lines
    subbricks = []
    for line in subbrick_lines:
        idx = int(line.split('#')[1].split()[0])
        name = line.split("'")[1]
        subbricks.append((idx, name))
        
    return subbricks

# Mask

In [4]:
Dir_working = '/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis'
Nvar = 113
NFA = 8
flag_model = f'Nvar{Nvar}NFA{NFA}_LPAC_multipleReg'

Dir_figures = f'/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/{flag_model}/figures_SVC/'
os.makedirs(Dir_figures,exist_ok=True)

# groupMask = '/work/desai-lab/xuanyang/Project/dataset/Nastase/narratives/derivatives/afni-nosmooth/tpl-MNI152NLin2009cAsym/nosmooth_mask_allstories.nii'
groupMask = '/work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz'
folder = 'threshold_GM'

In [5]:
Dir_working

'/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis'

In [6]:
Dir_model = os.path.join(Dir_working,'models',flag_model,f'FA{NFA}')
Dir_results = os.path.join(Dir_model,'results')
Dir_results_1st = os.path.join(Dir_results,'firstlevel')
Dir_results_2nd = os.path.join(Dir_results,'secondlevel')

for i,subID, task,label in zip(df_master.index,df_master.subID,df_master.task,df_master.label):
    idx = "{:03d}".format(i+1)
    Dir_sub_task = os.path.join(Dir_results_1st,subID,task)
    path_img_stats = os.path.join(Dir_sub_task,'{}.results'.format(subID),'stats.{}_REML+tlrc.BRIK'.format(subID))
    df_master.loc[i,'finished'] = 0

    if os.path.exists(path_img_stats):
        df_master.loc[i,'finished'] = 1
        df_master.loc[i,'img_stats'] = path_img_stats

subfolder = '{}highacc'.format(len(df_master))
subList_ana_cmplt = df_master.loc[df_master.finished==1].reset_index(drop=True)
Nsub = len(df_master)

df_subbricks = pd.DataFrame(get_subbricks_info(subList_ana_cmplt.img_stats[0]),columns=['imgIDList', 'regName'])
df_regModel = df_subbricks.loc[df_subbricks.regName.str.contains(f'_bin2345#0_Coef')].copy()
df_regModel['regName'] = df_regModel['regName'].str.replace('_bin2345#0_Coef',f'_{flag_model}')
df_regModel['regName'] = df_regModel['regName'] +'_'+subfolder
df_regModel

     imgIDList                                      regName
114        114  FA1_Nvar113NFA8_LPAC_multipleReg_213highacc
117        117  FA2_Nvar113NFA8_LPAC_multipleReg_213highacc
120        120  FA3_Nvar113NFA8_LPAC_multipleReg_213highacc
123        123  FA4_Nvar113NFA8_LPAC_multipleReg_213highacc
126        126  FA5_Nvar113NFA8_LPAC_multipleReg_213highacc
129        129  FA6_Nvar113NFA8_LPAC_multipleReg_213highacc
132        132  FA7_Nvar113NFA8_LPAC_multipleReg_213highacc
135        135  FA8_Nvar113NFA8_LPAC_multipleReg_213highacc

In [6]:
Dir_model = os.path.join(Dir_working,'models',flag_model,f'FA{NFA}')
Dir_results = os.path.join(Dir_model,'results')
Dir_results_1st = os.path.join(Dir_results,'firstlevel')
Dir_results_2nd = os.path.join(Dir_results,'secondlevel')

for i,subID, task,label in zip(df_master.index,df_master.subID,df_master.task,df_master.label):
    idx = "{:03d}".format(i+1)
    Dir_sub_task = os.path.join(Dir_results_1st,subID,task)
    path_img_stats = os.path.join(Dir_sub_task,'{}.results'.format(subID),'stats.{}_REML+tlrc.BRIK'.format(subID))
    df_master.loc[i,'finished'] = 0

    if os.path.exists(path_img_stats):
        df_master.loc[i,'finished'] = 1
        df_master.loc[i,'img_stats'] = path_img_stats

subfolder = '{}highacc'.format(len(df_master))
subList_ana_cmplt = df_master.loc[df_master.finished==1].reset_index(drop=True)
Nsub = len(df_master)

df_subbricks = pd.DataFrame(get_subbricks_info(subList_ana_cmplt.img_stats[0]),columns=['imgIDList', 'regName'])
df_regModel = df_subbricks.loc[df_subbricks.regName.str.contains(f'_bin2345#0_Coef')].copy()
df_regModel['regName'] = df_regModel['regName'].str.replace('_bin2345#0_Coef',f'_{flag_model}')
df_regModel['regName'] =df_regModel['regName'] +'_'+subfolder

for regName,imgID in zip(df_regModel['regName'],df_regModel['imgIDList']):

    resultDir_2nd = os.path.join(Dir_results_2nd,folder)
    masterScript = os.path.join(resultDir_2nd,'run_secondlevel_{}.sh'.format(subfolder))
    if not os.path.exists(resultDir_2nd):
        os.makedirs(resultDir_2nd)
    os.chdir(resultDir_2nd)
    scriptFile = os.path.join(resultDir_2nd,'Batch_secondlevel_'+regName)
    with open(scriptFile, "w") as f:
        f.write("#!/bin/tcsh -xef \n")
        f.write("/work/apps/AFNI/linux_openmp_64/3dttest++ -prefix {} \\\n".format(regName))
        f.write("-mask {} \\\n".format(groupMask))
        f.write("-ClustSim -seed 31415 \\\n")
        f.write("-setA {} \\\n".format(regName))
        for i,statImg in enumerate(subList_ana_cmplt.img_stats):
            statID = '0'+str(i+1) if (i+1<10) else str(i+1)
            f.write(f"{statID} {statImg.replace('.BRIK','')}'[{str(imgID)}]' \\\n")
#             f.write(f'/work/apps/AFNI/linux_openmp_64/3dAFNItoNIFTI {df_regModel.regName.values[0]}+tlrc.BRIK"[1]" -prefix {df_regModel.regName.values[0]}.nii')
    os.chdir(resultDir_2nd)
    run(f"tcsh {scriptFile}",shell=True)


List_files = [x for x in os.listdir(resultDir_2nd) if '.nii' in x or '+tlrc' in x]
for file in List_files:
    os.makedirs(os.path.join(Dir_figures,folder),exist_ok=True)
    shutil.copy(os.path.join(resultDir_2nd,file),os.path.join(Dir_figures,folder,file))

++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA1_Nvar113N_Zscr] = 6.99887e-08
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA1_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA1_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA1_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 37.8 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA2_Nvar113N_Zscr] = 5.61557e-06
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA2_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA2_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA2_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 12.0 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA3_Nvar113N_Zscr] = 0.00034006
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA3_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA3_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA3_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 9.5 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA4_Nvar113N_Zscr] = 1.4894e-06
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA4_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA4_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA4_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 9.0 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA5_Nvar113N_Zscr] = 0.0530362
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA5_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA5_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA5_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 9.3 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA6_Nvar113N_Zscr] = 9.02812e-11
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA6_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA6_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA6_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 9.2 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA7_Nvar113N_Zscr] = 0.000665369
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA7_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA7_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA7_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 9.7 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021
++ 3dttest++: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: Zhark++
++ 41229 voxels in -mask dataset
++ Number of -Clustsim threads set to 48
++ option -setA :: processing as LONG form (label label dset label dset ...)
++ have 213 volumes corresponding to option '-setA'
++ loading -setA datasets
*+ WARNING: 3dttest++ -setA :: 35 vectors are constant
++ t-testing:0123456789.0123456789.0123456789.0123456789.0123456789.!
 + skipped 35 voxels completely for having constant data
++ ---------- End of analyses -- freeing workspaces ----------
++ Creating FDR curves in output dataset
++ Smallest FDR q [1 FA8_Nvar113N_Zscr] = 0.000933012
 + Added 1 FDR curve to dataset
** ERROR: output dataset name 'FA8_Nvar113NFA8_LPAC_multipleReg_213highacc' conflicts with existing file
** ERROR: dataset NOT written to disk!
** ERROR: output dataset name 'FA8_Nvar113NFA8_LPAC_multipleReg_213highacc.resid.nii' conflicts with existing file
** ERROR: dataset NOT written to disk!
++ ================ Starting -ClustSim calculations ================
 + === temporary files will have prefix FA8_Nvar113NFA8_LPAC_multipleReg_213highacc ===
 + === running 48 -randomsign jobs (210 iterations per job) ===
 + === creating 831,176,640 (831 million) bytes of pseudo-data in .sdat files ===
 + --- 3dClustSim reads .sdat files to compute cluster-threshold statistics ---
 + --- there is 201,163,751,424 (201 billion) bytes of memory on your system ---
sh: 3dttest++: command not found
 + 3dttest++ ===== simulation jobs have finished (1.6 s elapsed)
 + 3dttest++ ===== starting 3dClustSim A: elapsed = 9.7 s
sh: 3dClustSim: command not found
** FATAL ERROR: ===== 3dClustSim command failed :-((( =====
** Program compile date = Apr  9 2021

In [7]:
Dir_figures

'/work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/'

In [18]:
subfolder = '{}highacc'.format(len(df_master))
os.chdir(os.path.join(Dir_figures,folder))
for iFA in range(1,NFA+1):#NFA+1
    file = f'FA{iFA}_{flag_model}_{subfolder}'
    script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dAFNItoNIFTI {file}+tlrc.BRIK"[0]" -prefix {file}.nii'
    run(f"tcsh {script}",shell=True)
    
    script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dcalc \
        -a {file}+tlrc.BRIK"[1]" \
        -expr "fizt_t2p(a) * step(a) - fizt_t2p(a) * step(-a)" \
        -prefix {file}_p.nii \
        -datum float'
    run(f"tcsh {script}",shell=True)

++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_p.nii

In [ ]:
        # get z-map
        file_input = os.path.join(Dir_figures,folder,f'FA{iFA}_{flag_model}_{subfolder}+tlrc')
        file_mask = os.path.join(Dir_output,f"{file.replace('_dat','_mask')}.nii")
        script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dcalc -a {file_input}.BRIK"[1]" -b {file_mask} -expr "a*b" -prefix {file}_z.nii'
        run(f"tcsh {script}",shell=True)

        # get p-map
        script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dcalc \
        -a {file}_z.nii \
        -expr "fizt_t2p(a) * step(a) - fizt_t2p(a) * step(-a)" \
        -prefix {file}_p.nii'
        run(f"tcsh {script}",shell=True)

In [9]:
for iFA in range(1,NFA+1):#NFA+1
    Dir_model = os.path.join(Dir_working,'models',flag_model,f'FA{NFA}')
    Dir_results = os.path.join(Dir_model,'results','secondlevel',folder)
    file = f"FA{iFA}_{flag_model}_{subfolder}.CSimA.NN2_bisided.1D"
    file_src = os.path.join(Dir_results,file)
    os.makedirs(os.path.join(Dir_figures,folder),exist_ok=True)
    file_dst = os.path.join(Dir_figures,folder,file)
    shutil.copy(file_src,file_dst)

# Clusterize threshold

In [33]:
NN = 2
sided = 'bisided'
os.chdir(os.path.join(Dir_figures,folder))

alpha = '0.05'
for iFA in range(1,NFA+1):#NFA+1
    file_table = os.path.join(Dir_figures,folder,f"FA{iFA}_{flag_model}_{subfolder}.CSimA.NN{NN}_{sided}.1D")
    df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
    new_row = pd.DataFrame([df.columns], columns=df.columns)
    df = pd.concat([new_row, df], ignore_index=True)
    df.columns = ['p']+[f"0.{11-x:02d}" for x in range(1,11)]
    
    for p in [0.001,0.005]: 
        if sided != '1sided':
            p = p*2 
            threshold_label = f"{sided}NN{NN}_1tailp{str(p/2)[2:]}"
        else:
            threshold_label = f"{sided}NN{NN}_1tailp{str(p)[2:]}"
            
            
        voxels = df.loc[df['p']==p,alpha].values[0]
        
        Dir_output = os.path.join(Dir_figures,folder,threshold_label)
        if not os.path.exists(Dir_output):
            os.makedirs(Dir_output)
        
        file_input = os.path.join(Dir_figures,folder,f'FA{iFA}_{flag_model}_{subfolder}+tlrc')
        file_output_dat = os.path.join(Dir_output,f'FA{iFA}_{flag_model}_{subfolder}_v{voxels}_dat')
        file_output_map = os.path.join(Dir_output,f'FA{iFA}_{flag_model}_{subfolder}_v{voxels}_ROI')
        file_output_1D = os.path.join(Dir_output,f'FA{iFA}_{flag_model}_{subfolder}_v{voxels}_ROI.1D')
        script = f"3dClusterize -inset {file_input} -mask {groupMask} -NN {NN} -ithr 1 -idat 0 -clust_nvox {voxels} -pref_dat {file_output_dat} -pref_map {file_output_map} -{sided} p={p} -1Dformat > {file_output_1D}"
        print(script)
        print('\n')
    #     script = f"#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dClusterize -inset {file_input} -NN {NN} -ithr 0 -clust_nvox {voxels} -pref_dat {file_output_dat} -thr_p {p}"
#     run(f"tcsh {script}",shell=True)

3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 18 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 55 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v55_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v55_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v55_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 17 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 53 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 17 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 56 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 18 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 61 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v61_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v61_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v61_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 18 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 56 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 18 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 54 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v54_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v54_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v54_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 17 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 58 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v58_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v58_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v58_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 17 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI -bisided p=0.002 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp001/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_ROI.1D


3dClusterize -inset /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc+tlrc -mask /work/desai-lab/xuanyang/Project/Semantic/analysis/FactorAnalysis/github/FactorAnalysis_fMRI/scripts/fMRI/masks/rs_mask_GM_33.nii.gz -NN 2 -ithr 1 -idat 0 -clust_nvox 53 -pref_dat /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_dat -pref_map /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_ROI -bisided p=0.01 -1Dformat > /work/desai-lab/xuanyang/Project/Semantic/analysis/ParametricModulation/Nastase/allstories/FactorAnalysis/models/Nvar113NFA8_LPAC_multipleReg/figures_SVC/threshold_GM/bisidedNN2_1tailp005/FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_ROI.1D

/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
/tmp/ipykernel_24620/749623023.py:8: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)

In [9]:
df_fig = []
for iFA in range(1,NFA+1):#NFA+1
    file_table = os.path.join(Dir_figures,folder,f"FA{iFA}_{flag_model}_{subfolder}.CSimA.NN{NN}_{sided}.1D")
    df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
    new_row = pd.DataFrame([df.columns], columns=df.columns)
    df = pd.concat([new_row, df], ignore_index=True)
    df.columns = ['p']+[f"0.{11-x:02d}" for x in range(1,11)]
    
    
    for p in [0.001,0.005]: 
        if sided != '1sided':
            p = p*2 
            threshold_label = f"{sided}NN{NN}_1tailp{str(p/2)[2:]}"
        else:
            threshold_label = f"{sided}NN{NN}_1tailp{str(p)[2:]}"
            
        
        voxels = df.loc[df['p']==p,alpha].values[0]
        
        Dir_output = os.path.join(Dir_figures,folder,threshold_label)
        
        os.chdir(Dir_output)

        file = f'FA{iFA}_{flag_model}_{subfolder}_v{voxels}_dat'
        # file_output_dat = os.path.join(Dir_output,file)
        script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dAFNItoNIFTI {file}+tlrc.BRIK"[0]" -prefix {file}.nii'
        run(f"tcsh {script}",shell=True)
        
        if not os.path.exists(os.path.join(Dir_output,f"{file.replace('_dat','_mask')}.nii")):
            command = f"/work/apps/AFNI/linux_openmp_64/3dcalc -a {file}.nii -expr 'step(abs(a))' -prefix {file.replace('_dat','_mask')}.nii"
            run(f"{command}",shell=True)

        # get z-map
        file_input = os.path.join(Dir_figures,folder,f'FA{iFA}_{flag_model}_{subfolder}+tlrc')
        file_mask = os.path.join(Dir_output,f"{file.replace('_dat','_mask')}.nii")
        script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dcalc -a {file_input}.BRIK"[1]" -b {file_mask} -expr "a*b" -prefix {file}_z.nii'
        run(f"tcsh {script}",shell=True)

        # get p-map
        script = f'#!/bin/tcsh -xef \n /work/apps/AFNI/linux_openmp_64/3dcalc \
        -a {file}_z.nii \
        -expr "fizt_t2p(a) * step(a) - fizt_t2p(a) * step(-a)" \
        -prefix {file}_p.nii'
        run(f"tcsh {script}",shell=True)

        # get min max
        script = f"/work/apps/AFNI/linux_openmp_64/3dinfo -min -max {os.path.join(Dir_output,file)}.nii"
        result = run(f"{script}",shell=True,capture_output=True, text=True)
        Min, Max = result.stdout.replace('\n','').split('\t')
        
        script = f"/work/apps/AFNI/linux_openmp_64/3dinfo -min -max {os.path.join(Dir_output,file)}_z.nii"
        result = run(f"{script}",shell=True,capture_output=True, text=True)
        Min_z, Max_z = result.stdout.replace('\n','').split('\t')

        script = f"/work/apps/AFNI/linux_openmp_64/3dinfo -min -max {os.path.join(Dir_output,file)}_p.nii"
        result = run(f"{script}",shell=True,capture_output=True, text=True)
        Min_p, Max_p = result.stdout.replace('\n','').split('\t')
        
        df_tmp = pd.DataFrame({'FA':iFA,'sided':sided,'p':p,
                               'min':Min,'max':Max,
                               'min_z':Min_z,'max_z':Max_z,
                               'min_p':Min_p,'max_p':Max_p},index=[0])
        df_fig.append(df_tmp)
df_fig = pd.concat(df_fig,ignore_index=True)

df_fig

/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v55_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA1_Nvar113NFA8_LPAC_multipleReg_213highacc_v55_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA2_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA3_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v61_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA4_Nvar113NFA8_LPAC_multipleReg_213highacc_v61_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA5_Nvar113NFA8_LPAC_multipleReg_213highacc_v56_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v18_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v54_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA6_Nvar113NFA8_LPAC_multipleReg_213highacc_v54_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v58_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA7_Nvar113NFA8_LPAC_multipleReg_213highacc_v58_dat_p.nii
/tmp/ipykernel_31277/3234548047.py:4: FutureWarning: The 'delim_whitespace' keyword in pd.read_csv is deprecated and will be removed in a future version. Use ``sep='\s+'`` instead
  df = pd.read_csv(file_table, delim_whitespace=True, skiprows=8)
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v17_dat_p.nii
++ 3dAFNItoNIFTI: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_dat_z.nii
++ 3dcalc: AFNI version=AFNI_21.1.01 (Apr  9 2021) [64-bit]
++ Authored by: A cast of thousands
++ Output dataset ./FA8_Nvar113NFA8_LPAC_multipleReg_213highacc_v53_dat_p.nii

,FA,sided,p,min,max,min_z,max_z,min_p,max_p
0,1,bisided,0.002,-0.410415,0.312243,-7.03343,4.88746,-0.00193105,0.00198311
1,1,bisided,0.010,-0.410415,0.312243,-7.03343,4.88746,-0.00989858,0.00996275
2,2,bisided,0.002,-0.488901,0.383209,-6.28229,5.37877,-0.00199809,0.00199985
3,2,bisided,0.010,-0.488901,0.383209,-6.28229,5.37877,-0.0099954,0.00991654
4,3,bisided,0.002,-0.26593,0,-5.67203,0,-0.00199661,0
5,3,bisided,0.010,-0.26593,0,-5.67203,0,-0.00999133,0
6,4,bisided,0.002,-0.236657,0.281416,-5.17801,6.57931,-0.00199406,0.00198198
7,4,bisided,0.010,-0.236657,0.281416,-5.17801,6.57931,-0.0099998,0.00993417
8,5,bisided,0.002,-0.274741,0.298245,-4.5414,4.43938,-0.00194626,0.00198918
9,5,bisided,0.010,-0.274741,0.279689,-4.5414,4.58011,-0.00987071,0.00990204
10,6,bisided,0.002,-0.495008,0.503555,-7.40711,7.87785,-0.00198616,0.00198862
11,6,bisided,0.010,-0.495008,0.503555,-7.40711,7.87785,-0.0099882,0.00997781
12,7,bisided,0.002,-0.24508,0.248542,-5.6231,4.79215,-0.00197312,0.00197818
13,7,bisided,0.010,-0.24508,0.248542,-5.6231,4.79215,-0.00998607,0.00986367
14,8,bisided,0.002,-0.1357,0.200549,-5.42855,5.39584,-0.00195807,0.00195892
15,8,bisided,0.010,-0.1357,0.200549,-5.42855,5.39584,-0.00998269,0.00999488

# BrainNet

In [10]:
df_fig.loc[df_fig['p']==0.002,'min'].min(),df_fig.loc[df_fig['p']==0.002,'max'].max()

('-0.1357', '0.503555')

In [11]:
df_fig.loc[df_fig['p']==0.01,'min'].min(),df_fig.loc[df_fig['p']==0.01,'max'].max()

('-0.1357', '0.503555')

# Recode FA7 for visualization

In [28]:
import shutil
# backup
List_files = [x for x in os.listdir(os.path.join(Dir_figures,folder)) if 'FA7' in x and '.nii' in x and 'resid' not in x]
for file in List_files:
    file1 = os.path.join(Dir_figures,folder,file)
    file2 = os.path.join(Dir_figures,folder,file.replace('.nii','_raw.nii'))
    if not os.path.exists(file2):
        # shutil.copy(file1,file2)
        os.rename(file1,file2)

In [31]:
List_files = [x for x in os.listdir(os.path.join(Dir_figures,folder)) if 'FA7' in x and '.nii' in x and 'resid' not in x]
for file in List_files:
    script = f"/work/apps/AFNI/linux_openmp_64/3dcalc -a {os.path.join(Dir_figures,folder,file)} -expr '-a' -prefix {os.path.join(Dir_figures,folder,file.replace('_raw.nii','.nii'))}"
    result = run(f"{script}",shell=True,capture_output=True, text=True)